services:
  - type: web
    name: deepfake-detection
    env: docker
    repo: https://github.com/YOUR_GITHUB_USERNAME/YOUR_REPOSITORY_NAME.git # Replace with your repository URL
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 10
